Update AutoTagging.yml

diff --git a/.github/workflows/AutoTagging.yml b/.github/workflows/AutoTagging.yml
--- a/.github/workflows/AutoTagging.yml
+++ b/.github/workflows/AutoTagging.yml
@@ -1,39 +1,51 @@
 name: Merge Branch
+
 on:
   workflow_dispatch:
     inputs:
       from_branch:
-        description: 'Source branch from '
+        description: 'Source branch to merge labels from'
         required: true
       to_branch:
-        description: 'Destination branch '
+        description: 'Destination branch to merge labels into'
         required: true
       tag_name:
         description: 'Name for the tag to be created'
         required: true
 
 jobs:
-  merge_labels:
+  merge_labels_and_create_tag:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
 
-      - name: Merge Branch
+      - name: Debug Information
         run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
+          echo "FROM_BRANCH: ${{ github.event.inputs.from_branch }}"
+          echo "TO_BRANCH: ${{ github.event.inputs.to_branch }}"
+          echo "TAG_NAME: ${{ github.event.inputs.tag_name }}"
+          git branch -a
+          git fetch --all
+          git branch -a
+          
+      - name: Merge labels
+        run: |
           FROM_BRANCH=${{ github.event.inputs.from_branch }}
           TO_BRANCH=${{ github.event.inputs.to_branch }}
-          git checkout ${TO_BRANCH}
-          git merge --no-ff --no-edit ${FROM_BRANCH}
-          git push origin ${TO_BRANCH}
+          git checkout $TO_BRANCH || { echo "Failed to checkout $TO_BRANCH"; exit 1; }
+          git merge --no-ff --no-edit $FROM_BRANCH || { echo "Failed to merge $FROM_BRANCH into $TO_BRANCH"; exit 1; }
+          git push origin $TO_BRANCH || { echo "Failed to push changes to $TO_BRANCH"; exit 1; }
           
       - name: Create Tag
         run: |
           TAG_NAME=${{ github.event.inputs.tag_name }}
           COMMIT_ID=$(git rev-parse --short HEAD)
-          git tag $TAG_NAME-$COMMIT_ID
-          git push origin $TAG_NAME-$COMMIT_ID
+          git tag $TAG_NAME-$COMMIT_ID || { echo "Failed to create tag"; exit 1; }
+          git push origin $TAG_NAME-$COMMIT_ID || { echo "Failed to push tag"; exit 1; }
+          
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    
 
           
